defaults: &defaults
  app_name: "桌球愛好者聯盟"
  domain: ""
  facebook_app_id:
  facebook_secret:
  hipchat_token:
  hipchat_room_name:
  admin_emails:
    - ""
  google_analytics_key: ""
  default_logo_url: "/LTTF_logo.png"
  email_sender: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
